// <auto-generated />
namespace LootCrate4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatedSurveysModle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedSurveysModle));
        
        string IMigrationMetadata.Id
        {
            get { return "201602251811517_updatedSurveysModle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
